// <auto-generated />
using System;
using DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A_DAL.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231129105617_context")]
    partial class context
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("A_DAL.Models.GiamGia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("PhanTramGiamGia")
                        .HasColumnType("int");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("DAL.Models.Admin", b =>
                {
                    b.Property<Guid>("IdAdmin")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<bool?>("HienThi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("IdAdmin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DAL.Models.CaKham", b =>
                {
                    b.Property<Guid>("IdCaKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("STTCaKham")
                        .HasColumnType("int");

                    b.HasKey("IdCaKham");

                    b.ToTable("CaKham");
                });

            modelBuilder.Entity("DAL.Models.ChamCong", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("TrangThaiCham")
                        .HasColumnType("bit");

                    b.HasKey("IdNhanVien");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("DAL.Models.DanhGia", b =>
                {
                    b.Property<Guid>("IdDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("HienThi")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdPhieuKham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDanhGia");

                    b.HasIndex("IdPhieuKham");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("DAL.Models.DichVu", b =>
                {
                    b.Property<Guid>("IdDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<bool?>("HienThi")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDichVu");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HienThi")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("IdHoaDon");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DAL.Models.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPhieuKham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdHoaDon", "IdPhieuKham");

                    b.HasIndex("IdPhieuKham");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("DAL.Models.KhachHang", b =>
                {
                    b.Property<Guid>("IdKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<bool?>("HienThi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DAL.Models.LichSuKham", b =>
                {
                    b.Property<Guid>("IdPhieuKham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPhieuKham");

                    b.ToTable("LichSuKham");
                });

            modelBuilder.Entity("DAL.Models.Luong", b =>
                {
                    b.Property<Guid>("IdLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoCong")
                        .HasColumnType("int");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<int?>("Thuong")
                        .HasColumnType("int");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdLuong");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("IdNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaKhamIdCaKham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChucVu")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<bool?>("HienThi")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PhongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdNhanVien");

                    b.HasIndex("CaKhamIdCaKham");

                    b.HasIndex("PhongId");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DAL.Models.PhieuKham", b =>
                {
                    b.Property<Guid>("IdPhieuKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("HienThi")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdBacSi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCaKham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDichVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdNgay")
                        .HasColumnType("int");

                    b.Property<Guid>("IdPhong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdYTa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdPhieuKham");

                    b.HasIndex("IdCaKham");

                    b.HasIndex("IdDichVu");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdNgay");

                    b.HasIndex("IdPhong");

                    b.ToTable("PhieuKham");
                });

            modelBuilder.Entity("DAL.Models.Phong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("DAL.Models.ThongBao", b =>
                {
                    b.Property<Guid>("IdThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ChapNhan")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdNguoiGui")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TinNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdThongBao");

                    b.HasIndex("IdNguoiGui");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("DAL.Models.ThongKe", b =>
                {
                    b.Property<Guid>("IdThongKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLuong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LoaiThongKe")
                        .HasColumnType("bit");

                    b.HasKey("IdThongKe");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdLuong");

                    b.ToTable("ThongKe");
                });

            modelBuilder.Entity("DAL.Models.TrangThaiNhanVien", b =>
                {
                    b.Property<int>("IdNgay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNgay"));

                    b.Property<Guid>("IdCaKham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdNgay");

                    b.HasIndex("IdCaKham");

                    b.HasIndex("IdNhanVien");

                    b.ToTable("TrangThaiNhanVien");
                });

            modelBuilder.Entity("DAL.Models.TrangThaiPhong", b =>
                {
                    b.Property<int>("IdNgay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNgay"));

                    b.Property<Guid>("IdCaKham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdPhong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdNgay");

                    b.HasIndex("IdCaKham");

                    b.HasIndex("IdPhong");

                    b.ToTable("TrangThaiPhong");
                });

            modelBuilder.Entity("DAL.Models.Admin", b =>
                {
                    b.HasOne("DAL.Models.NhanVien", "NhanVien")
                        .WithOne("Admin")
                        .HasForeignKey("DAL.Models.Admin", "IdAdmin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL.Models.ChamCong", b =>
                {
                    b.HasOne("DAL.Models.NhanVien", "NhanVien")
                        .WithOne("ChamCong")
                        .HasForeignKey("DAL.Models.ChamCong", "IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL.Models.DanhGia", b =>
                {
                    b.HasOne("DAL.Models.PhieuKham", "PhieuKham")
                        .WithMany("Rate")
                        .HasForeignKey("IdPhieuKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.HasOne("DAL.Models.NhanVien", "NV")
                        .WithMany("HoaDon")
                        .HasForeignKey("IdNhanVien");

                    b.Navigation("NV");
                });

            modelBuilder.Entity("DAL.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("DAL.Models.HoaDon", "Bill")
                        .WithMany("HoaDonChiTiet")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.PhieuKham", "MedicalBills")
                        .WithMany("BillDetail")
                        .HasForeignKey("IdPhieuKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("MedicalBills");
                });

            modelBuilder.Entity("DAL.Models.LichSuKham", b =>
                {
                    b.HasOne("DAL.Models.PhieuKham", "MedicalBills")
                        .WithOne("HealtRecord")
                        .HasForeignKey("DAL.Models.LichSuKham", "IdPhieuKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalBills");
                });

            modelBuilder.Entity("DAL.Models.Luong", b =>
                {
                    b.HasOne("DAL.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.HasOne("DAL.Models.CaKham", "CaKham")
                        .WithMany("NhanViens")
                        .HasForeignKey("CaKhamIdCaKham");

                    b.HasOne("DAL.Models.Phong", "Phong")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongId");

                    b.Navigation("CaKham");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DAL.Models.PhieuKham", b =>
                {
                    b.HasOne("DAL.Models.CaKham", "Shifts")
                        .WithMany("PhieuKham")
                        .HasForeignKey("IdCaKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.DichVu", "Service")
                        .WithMany("MedicalBills")
                        .HasForeignKey("IdDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.KhachHang", "Customers")
                        .WithMany("MedicalBill")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.TrangThaiNhanVien", "TrangThaiNhanVien")
                        .WithMany("PhieuKham")
                        .HasForeignKey("IdNgay");

                    b.HasOne("DAL.Models.Phong", "Clinic")
                        .WithMany("PhieuKhams")
                        .HasForeignKey("IdPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Customers");

                    b.Navigation("Service");

                    b.Navigation("Shifts");

                    b.Navigation("TrangThaiNhanVien");
                });

            modelBuilder.Entity("DAL.Models.ThongBao", b =>
                {
                    b.HasOne("DAL.Models.NhanVien", "Staff")
                        .WithMany("ThongBao")
                        .HasForeignKey("IdNguoiGui")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DAL.Models.ThongKe", b =>
                {
                    b.HasOne("DAL.Models.HoaDon", "HoaDon")
                        .WithMany("ThongKe")
                        .HasForeignKey("IdHoaDon");

                    b.HasOne("DAL.Models.Luong", "Luong")
                        .WithMany("ThongKe")
                        .HasForeignKey("IdLuong");

                    b.Navigation("HoaDon");

                    b.Navigation("Luong");
                });

            modelBuilder.Entity("DAL.Models.TrangThaiNhanVien", b =>
                {
                    b.HasOne("DAL.Models.CaKham", "Shift")
                        .WithMany("TrangThaiNhanVien")
                        .HasForeignKey("IdCaKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.NhanVien", "NhanVien")
                        .WithMany("TrangThaiNhanVien")
                        .HasForeignKey("IdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("DAL.Models.TrangThaiPhong", b =>
                {
                    b.HasOne("DAL.Models.CaKham", "CaKham")
                        .WithMany("TrangThaiPhong")
                        .HasForeignKey("IdCaKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Phong", "Phong")
                        .WithMany("TrangThaiPhongs")
                        .HasForeignKey("IdPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaKham");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DAL.Models.CaKham", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("PhieuKham");

                    b.Navigation("TrangThaiNhanVien");

                    b.Navigation("TrangThaiPhong");
                });

            modelBuilder.Entity("DAL.Models.DichVu", b =>
                {
                    b.Navigation("MedicalBills");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiet");

                    b.Navigation("ThongKe");
                });

            modelBuilder.Entity("DAL.Models.KhachHang", b =>
                {
                    b.Navigation("MedicalBill");
                });

            modelBuilder.Entity("DAL.Models.Luong", b =>
                {
                    b.Navigation("ThongKe");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("ChamCong");

                    b.Navigation("HoaDon");

                    b.Navigation("ThongBao");

                    b.Navigation("TrangThaiNhanVien");
                });

            modelBuilder.Entity("DAL.Models.PhieuKham", b =>
                {
                    b.Navigation("BillDetail");

                    b.Navigation("HealtRecord");

                    b.Navigation("Rate");
                });

            modelBuilder.Entity("DAL.Models.Phong", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("PhieuKhams");

                    b.Navigation("TrangThaiPhongs");
                });

            modelBuilder.Entity("DAL.Models.TrangThaiNhanVien", b =>
                {
                    b.Navigation("PhieuKham");
                });
#pragma warning restore 612, 618
        }
    }
}
